# Don't run these tasks for all crates in the workspace.
[config]
default_to_workspace = false

# Build package in no_std environment.
[tasks.no-std]
command = "cargo"
args = ["build", "--target", "thumbv7m-none-eabi"]

# Build docs for docs.rs.
[tasks.docsrs]
toolchain = "nightly"
command = "cargo"
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
args = ["doc", "--all-features", "--open"]

# Lint all features.
[tasks.lint]
command = "cargo"
args = ["clippy", "--all-features"]

# Run tests under miri.
# NOTE: must run as: cargo +nightly make miri
[tasks.miri-test]
toolchain = "nightly"
install_crate = { rustup_component_name = "miri" }
command = "cargo"
args = ["miri", "test", "--features", "thread_local"]

# Run Loom tests.
[tasks.loom-test]
command = "cargo"
env = { "RUSTFLAGS" = "--cfg loom" }
args = ["test", "--lib", "--release", "--features", "thread_local"]

# Lint Loom cfg.
[tasks.loom-lint]
command = "cargo"
env = { "RUSTFLAGS" = "--cfg loom" }
args = ["clippy", "--profile", "test", "--features", "thread_local"]

# Run busy loop bench.
[tasks.bench-busy]
command = "cargo"
args = ["bench", "--package", "benches", "--bench", "busy"]

# Run yield loop bench.
[tasks.bench-yield]
command = "cargo"
args = ["bench", "--package", "benches", "--bench", "yield", "--features", "mcslock/yield"]
