[env]
CFG_LOOM = "--cfg loom"
CLIPPY_FLAGS = "-D clippy::pedantic -D clippy::nursery"
CLIPPY_FLAGS_LOOM = "${CFG_LOOM} ${CLIPPY_FLAGS}"

# Don't run these tasks for all crates in the workspace.
[config]
default_to_workspace = false

# Build package for no_std environment.
[tasks.no-std]
command = "cargo"
args = ["hack", "build", "--target", "thumbv7m-none-eabi", "--no-dev-deps",
        "--feature-powerset", "--skip", "yield,thread_local"]

# Build docs for docs.rs.
[tasks.docsrs]
toolchain = "nightly"
command = "cargo"
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
args = ["doc", "--all-features", "--open"]

# Lint all feature combinations with cargo-hack.
[tasks.lint]
command = "cargo"
env = { "RUSTFLAGS" = "${CLIPPY_FLAGS}" }
args = ["hack", "clippy", "--feature-powerset", "--no-dev-deps"]

# Run tests under miri.
# NOTE: must run as: cargo +nightly make miri
[tasks.miri-test]
toolchain = "nightly"
install_crate = { rustup_component_name = "miri" }
command = "cargo"
args = ["miri", "test", "--all-features"]

# Run Loom tests.
[tasks.loom-test]
command = "cargo"
env = { "RUSTFLAGS" = "${CFG_LOOM}" }
args = ["test", "--lib", "--release", "--all-features"]

# Lint Loom cfg.
[tasks.loom-lint]
command = "cargo"
env = { "RUSTFLAGS" = "${CLIPPY_FLAGS_LOOM}" }
args = ["clippy", "--profile", "test", "--all-features"]

# Run busy loop bench.
[tasks.bench-busy]
command = "cargo"
args = ["bench", "--package", "benches", "--bench", "busy"]

# Run yield loop bench.
[tasks.bench-yield]
command = "cargo"
args = ["bench", "--package", "benches", "--bench", "yield", "--features", "mcslock/yield"]
