use core::cell::RefCell;

use super::{Mutex, MutexGuard, MutexNode};
use crate::cfg::thread::LocalKey;
use crate::inner;
use crate::parking::park::Park;

#[cfg(test)]
use crate::test::{LockNew, LockWith};

type StaticNode = &'static LocalMutexNode;

/// Declares a new [`parking::LocalMutexNode`] key, which is a handle to the
/// thread local node of the currently running thread.
///
/// The macro wraps any number of static declarations and make them thread
/// local. Each provided name is associated with a single thread local key. The
/// keys are wrapped and managed by the [`LocalMutexNode`] type, which are the
/// actual handles meant to be used with the `lock_with_local` API family from
/// [`parking::Mutex`]. Handles are provided by reference to functions.
///
/// See: [`try_lock_with_local`], [`lock_with_local`],
/// [`try_lock_with_local_unchecked`] or [`lock_with_local_unchecked`].
///
/// The thread local node definition generated by this macro avoids lazy
/// initialization and does not need to be dropped, which enables a more
/// efficient underlying implementation. See [`std::thread_local!`] macro.
///
/// # Sintax
///
/// * Allows multiple static definitions, must be separated with semicolons.
/// * Visibility is optional (private by default).
/// * Requires `static` keyword and a **UPPER_SNAKE_CASE** name.
///
/// # Example
///
/// ```
/// use mcslock::parking::spins::Mutex;
///
/// // Multiple difenitions.
/// mcslock::thread_local_parking_node! {
///     pub static NODE;
///     static OTHER_NODE1;
/// }
///
/// // Single definition.
/// mcslock::thread_local_parking_node!(pub static OTHER_NODE2);
///
/// let mutex = Mutex::new(0);
/// // Keys are provided to APIs by reference.
/// mutex.lock_with_local(&NODE, |mut guard| *guard = 10);
/// assert_eq!(mutex.lock_with_local(&NODE, |guard| *guard), 10);
/// ```
/// [`parking::Mutex`]: Mutex
/// [`parking::LocalMutexNode`]: LocalMutexNode
/// [`std::thread_local!`]: https://doc.rust-lang.org/std/macro.thread_local.html
/// [`try_lock_with_local`]: Mutex::try_lock_with_local
/// [`lock_with_local`]: Mutex::lock_with_local
/// [`try_lock_with_local_unchecked`]: Mutex::try_lock_with_local_unchecked
/// [`lock_with_local_unchecked`]: Mutex::lock_with_local_unchecked
#[macro_export]
macro_rules! thread_local_parking_node {
    // Empty (base for recursion).
    () => {};
    // Process multiply definitions (recursive).
    ($vis:vis static $node:ident; $($rest:tt)*) => {
        $crate::__thread_local_node_inner!($vis $node, parking);
        $crate::thread_local_parking_node!($($rest)*);
    };
    // Process single declaration.
    ($vis:vis static $node:ident) => {
        $crate::__thread_local_node_inner!($vis $node, parking);
    };
}

/// TODO: Docs
#[repr(transparent)]
#[derive(Debug)]
pub struct LocalMutexNode {
    inner: inner::LocalMutexNode<MutexNode>,
}

#[cfg(not(tarpaulin_include))]
impl LocalMutexNode {
    /// Creates a new `LocalMutexNode` key from the provided thread local node
    /// key.
    ///
    /// This function is **NOT** part of the public API and so must not be
    /// called directly by user's code. It is subjected to changes **WITHOUT**
    /// prior notice or accompanied with relevant SemVer changes.
    #[cfg(not(all(loom, test)))]
    #[doc(hidden)]
    #[must_use]
    #[inline(always)]
    pub const fn __new(key: LocalKey<RefCell<MutexNode>>) -> Self {
        let inner = inner::LocalMutexNode::new(key);
        Self { inner }
    }

    /// Creates a new Loom based `LocalMutexNode` key from the provided thread
    /// local node key (non-const).
    #[cfg(all(loom, test))]
    pub(crate) const fn new(key: &'static LocalKey<RefCell<MutexNode>>) -> Self {
        let inner = inner::LocalMutexNode::new(key);
        Self { inner }
    }
}

impl<T: ?Sized, P: Park> Mutex<T, P> {
    #[inline]
    #[track_caller]
    /// Attempts to acquire this mutex and then runs a closure against its guard.
    pub fn try_lock_with_local<F, Ret>(&self, node: StaticNode, f: F) -> Ret
    where
        F: FnOnce(Option<MutexGuard<'_, T, P>>) -> Ret,
    {
        self.inner.try_lock_with_local(&node.inner, |guard| f(guard.map(From::from)))
    }

    /// Attempts to acquire this mutex and then runs a closure against its guard.
    ///
    /// # Safety
    ///
    /// Unlike [`try_lock_with_local`], this method is unsafe because it does
    /// not check if the current thread local node is already mutably borrowed.
    /// If the current thread local node is already borrowed, calling this
    /// function is undefined behavior.
    ///
    /// [`try_lock_with_local`]: Mutex::try_lock_with_local
    #[inline]
    pub unsafe fn try_lock_with_local_unchecked<F, Ret>(&self, node: StaticNode, f: F) -> Ret
    where
        F: FnOnce(Option<MutexGuard<'_, T, P>>) -> Ret,
    {
        self.inner.try_lock_with_local_unchecked(&node.inner, |guard| f(guard.map(From::from)))
    }

    /// Acquires this mutex and then runs the closure against its guard.
    #[inline]
    #[track_caller]
    pub fn lock_with_local<F, Ret>(&self, node: StaticNode, f: F) -> Ret
    where
        F: FnOnce(MutexGuard<'_, T, P>) -> Ret,
    {
        self.inner.lock_with_local(&node.inner, |guard| f(From::from(guard)))
    }

    /// Acquires this mutex and then runs the closure against its guard.
    ///
    /// # Safety
    ///
    /// Unlike [`lock_with_local`], this method is unsafe because it does not
    /// check if the current thread local node is already mutably borrowed. If
    /// the current thread local node is already borrowed, calling this
    /// function is undefined behavior.
    ///
    /// [`lock_with_local`]: Mutex::lock_with_local
    #[inline]
    pub unsafe fn lock_with_local_unchecked<F, Ret>(&self, node: StaticNode, f: F) -> Ret
    where
        F: FnOnce(MutexGuard<'_, T, P>) -> Ret,
    {
        self.inner.lock_with_local_unchecked(&node.inner, |guard| f(From::from(guard)))
    }
}
// A thread local node definition used for testing.
#[cfg(test)]
#[cfg(not(tarpaulin_include))]
thread_local_parking_node!(static TEST_NODE);

/// A Mutex wrapper type that calls `lock_with_local` and
/// `try_lock_with_local` when implementing testing traits.
#[cfg(test)]
struct MutexPanic<T: ?Sized, P>(Mutex<T, P>);

#[cfg(test)]
impl<T: ?Sized, P> LockNew for MutexPanic<T, P> {
    type Target = T;

    fn new(value: Self::Target) -> Self
    where
        Self::Target: Sized,
    {
        Self(Mutex::new(value))
    }
}

#[cfg(test)]
impl<T: ?Sized, P: Park> LockWith for MutexPanic<T, P> {
    type Guard<'a> = MutexGuard<'a, Self::Target, P>
    where
        Self: 'a,
        Self::Target: 'a;

    fn try_lock_with<F, Ret>(&self, f: F) -> Ret
    where
        F: FnOnce(Option<MutexGuard<'_, T, P>>) -> Ret,
    {
        self.0.try_lock_with_local(&TEST_NODE, f)
    }

    fn lock_with<F, Ret>(&self, f: F) -> Ret
    where
        F: FnOnce(MutexGuard<'_, T, P>) -> Ret,
    {
        self.0.lock_with_local(&TEST_NODE, f)
    }

    fn is_locked(&self) -> bool {
        self.0.is_locked()
    }
}

/// A Mutex wrapper type that calls `lock_with_local_unchecked` and
/// `try_lock_with_local_unchecked` when implementing testing traits.
#[cfg(test)]
struct MutexUnchecked<T: ?Sized, P>(Mutex<T, P>);

#[cfg(test)]
impl<T: ?Sized, P> LockNew for MutexUnchecked<T, P> {
    type Target = T;

    fn new(value: Self::Target) -> Self
    where
        Self::Target: Sized,
    {
        Self(Mutex::new(value))
    }
}

#[cfg(test)]
impl<T: ?Sized, P: Park> LockWith for MutexUnchecked<T, P> {
    type Guard<'a> = MutexGuard<'a, Self::Target, P>
    where
        Self: 'a,
        Self::Target: 'a;

    fn try_lock_with<F, Ret>(&self, f: F) -> Ret
    where
        F: FnOnce(Option<MutexGuard<'_, T, P>>) -> Ret,
    {
        // SAFETY: caller must guarantee that this thread local node is not
        // already mutably borrowed for some other lock acquisition.
        unsafe { self.0.try_lock_with_local_unchecked(&TEST_NODE, f) }
    }

    fn lock_with<F, Ret>(&self, f: F) -> Ret
    where
        F: FnOnce(MutexGuard<'_, T, P>) -> Ret,
    {
        // SAFETY: caller must guarantee that this thread local node is not
        // already mutably borrowed for some other lock acquisition.
        unsafe { self.0.lock_with_local_unchecked(&TEST_NODE, f) }
    }

    fn is_locked(&self) -> bool {
        self.0.is_locked()
    }
}

#[cfg(all(not(loom), test))]
mod test {
    use crate::parking::park::{ImmediatePark, YieldThanPark};
    use crate::parking::MutexNode;
    use crate::test::tests;

    type MutexPanic<T> = super::MutexPanic<T, ImmediatePark>;
    type MutexUnchecked<T> = super::MutexUnchecked<T, ImmediatePark>;

    #[test]
    fn ref_cell_node_drop_does_not_matter() {
        use core::{cell::RefCell, mem};
        assert!(!mem::needs_drop::<RefCell<MutexNode>>());
    }

    #[test]
    fn lots_and_lots_immediate_park() {
        tests::lots_and_lots::<super::MutexPanic<_, ImmediatePark>>();
    }

    #[test]
    fn lots_and_lots_yield_than_park() {
        tests::lots_and_lots::<super::MutexPanic<_, YieldThanPark>>();
    }

    #[test]
    fn lots_and_lots_immediate_park_unchecked() {
        tests::lots_and_lots::<super::MutexUnchecked<_, ImmediatePark>>();
    }

    #[test]
    fn lots_and_lots_yield_than_park_unchecked() {
        tests::lots_and_lots::<super::MutexUnchecked<_, YieldThanPark>>();
    }

    #[test]
    fn smoke() {
        tests::smoke::<MutexPanic<_>>();
    }

    #[test]
    fn smoke_unchecked() {
        tests::smoke::<MutexUnchecked<_>>();
    }

    #[test]
    fn test_try_lock() {
        tests::test_try_lock::<MutexPanic<_>>();
    }

    #[test]
    fn test_try_lock_unchecked() {
        tests::test_try_lock::<MutexUnchecked<_>>();
    }

    #[test]
    #[should_panic = already_borrowed_error!()]
    fn test_lock_arc_nested() {
        tests::test_lock_arc_nested::<MutexPanic<_>, MutexPanic<_>>();
    }

    #[test]
    #[should_panic = already_borrowed_error!()]
    fn test_acquire_more_than_one_lock() {
        tests::test_acquire_more_than_one_lock::<MutexPanic<_>>();
    }

    #[test]
    fn test_lock_arc_access_in_unwind() {
        tests::test_lock_arc_access_in_unwind::<MutexPanic<_>>();
    }

    #[test]
    fn test_lock_arc_access_in_unwind_unchecked() {
        tests::test_lock_arc_access_in_unwind::<MutexUnchecked<_>>();
    }

    #[test]
    fn test_lock_unsized() {
        tests::test_lock_unsized::<MutexPanic<_>>();
    }

    #[test]
    fn test_lock_unsized_unchecked() {
        tests::test_lock_unsized::<MutexUnchecked<_>>();
    }
}

#[cfg(all(loom, test))]
mod model {
    use crate::loom::models;
    use crate::parking::park::{ImmediatePark, YieldThanPark};

    type MutexImmediatePanic<T> = super::MutexPanic<T, ImmediatePark>;
    type MutexImmediateUnchecked<T> = super::MutexUnchecked<T, ImmediatePark>;

    type MutexYieldPanic<T> = super::MutexPanic<T, YieldThanPark>;
    type MutexYieldUnchecked<T> = super::MutexUnchecked<T, YieldThanPark>;

    #[test]
    fn try_lock_join_immediate_park() {
        models::try_lock_join::<MutexImmediatePanic<_>>();
    }

    #[test]
    fn try_lock_join_yield_than_park() {
        models::try_lock_join::<MutexYieldPanic<_>>();
    }

    #[test]
    fn try_lock_join_immediate_park_unchecked() {
        models::try_lock_join::<MutexImmediateUnchecked<_>>();
    }

    #[test]
    fn try_lock_join_yield_than_park_unchecked() {
        models::try_lock_join::<MutexYieldUnchecked<_>>();
    }

    #[test]
    fn lock_join_immediate_park() {
        models::lock_join::<MutexImmediatePanic<_>>();
    }

    #[test]
    fn lock_join_yield_than_park() {
        models::lock_join::<MutexYieldPanic<_>>();
    }

    #[test]
    fn lock_join_immediate_park_unchecked() {
        models::lock_join::<MutexImmediateUnchecked<_>>();
    }

    #[test]
    fn mixed_lock_join_immediate_park() {
        models::mixed_lock_join::<MutexImmediatePanic<_>>();
    }

    #[test]
    fn mixed_lock_join_yield_than_park() {
        models::mixed_lock_join::<MutexYieldPanic<_>>();
    }

    #[test]
    fn mixed_lock_join_immediate_park_unchecked() {
        models::mixed_lock_join::<MutexImmediateUnchecked<_>>();
    }

    #[test]
    fn mixed_lock_join_yield_park_unchecked() {
        models::mixed_lock_join::<MutexYieldUnchecked<_>>();
    }
}
